# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./include/Spectograph.h
SOURCES += ./src/main.cpp \
    ./src/Spectograph.cpp
RESOURCES += Spectograph.qrc
